version: '2'
services:
  front:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .:/home/projects/docker-skeleton:ro
#      - ./docker/front/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/front/minimal.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default

  engine:
    build: ./docker/engine/
    volumes:
      - .:/home/projects/docker-skeleton:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /home/projects/docker-skeleton
    networks:
      - default
    dns_search:
      - engine

  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my_root_password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_DATABASE=user_password
    volumes:
      - db:/var/lib/mysql:rw
    networks:
      - default
    dns_search:
      - db
volumes:
  db: {}
networks:
  default: {}
